name: chemostat
version: '0.1.0.0'
description: chemostat model
author: Thaddäus Töppen
copyright: 2017 Thaddäus Töppen
license: BSD3
default-extensions:
- NoImplicitPrelude
dependencies:
- base >=4.7 && <5
- hmatrix
- hmatrix-gsl
- Chart
- Chart-cairo
- time
- foundation
library:
  source-dirs: src
  ghc-options: -O2 #-Wall -freverse-errors
  exposed-modules:
  - Chemostat
  - Util
executables:
  diffeq-hs:
    main: Main.hs
    source-dirs: src
    ghc-options: -O2 #-Wall -freverse-errors
