name: chemostat
version: '0.1.0.0'
description: Chemostat model implemented in Haskell using GSL bindings from HMatrix.
author: Thaddäus Töppen
copyright: 2017 Thaddäus Töppen
license: BSD3
default-extensions:
- NoImplicitPrelude
- OverloadedStrings
dependencies:
- base >=4.10 && <5
- hmatrix
- hmatrix-gsl
- foundation
- vector
- matplotlib
executables:
  chemostat:
    main: Main.hs
    source-dirs: src
    ghc-options: -O2
